
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  warning: 250
  error: 400
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true